#!/bin/bash
#
# chkconfig: 35 90 12
# description: go-monitor server
#
# Get function from functions library
. /etc/init.d/functions
# Start the service go-monitor
start() {
        initlog -c "echo -n Starting go-monitor server: "
        /usr/local/etc/go-monitor &
        ### Create the lock file ###
        touch /var/lock/subsys/go-monitor
        success $"go-monitor server startup"
        echo
}
# Restart the service 
stop() {
        initlog -c "echo -n Stopping go-monitor server: "
        killproc go-monitor
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/go-monitor
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status MAT
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
